---
title: "Ch3Wildfire_Environmental"
output: html_document
date: "2024-06-19"
---

# Load Packages
```{r}
library(tidyverse)
library(dplyr)
library(geosphere)
library(factoextra)
library(gglm)
library(pheatmap)
library(Hmisc)
library(gridExtra)
library(RColorBrewer)
library(grid)
library(broom)
library(cowplot)
library(lubridate)
```

# PHYSICOCHEMICAL DATA
```{r}
chem_wildfire <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/chem_wildfire.RDS")

#Generate a data frame with the full names of all the variables profiled
variables <- tribble(~Variable, ~Variable2,
  "Moisture", "Gravimetric Soil Moisture (%)",
  "SoilpH", "1:1 Soil pH",
  "WDRFBuffer", "WDRF Buffer pH",
  "SolubleSalt", "1:1 Soluble Salts (mmho/cm)",
  "OrganicMatter", "Organic Matter (% LOI)",
  "CO2C", "Soil Respiration CO2-C (ppm C)",
  "TotalN", "Total Nitrogen (ppm N)",
  "OrganicN", "Organic Nitrogen (ppm N)",
  "TotalOrganicC", "Total Organic Carbon (ppm C)",
  "Nitrate", "Nitrate (ppm NO3-N)",
  "Ammonium", "Ammonium (ppm NH4-N)",
  "InorganicNitrogen", "Inorganic Nitrogen (ppm N)",
  "TotalPhosphorus", "Total (ICAP) Phosphorus (ppm P)",
  "InorganicPhosphorus", "Inorganic (FIA) Phosphorus (ppm P)",
  "OrganicPhosphorus", "Organic Phosphorus (ppm P)",
  "Potassium", "ICAP Potassium (ppm K)",
  "Calcium", "ICAP Calcium (ppm Ca)",
  "Aluminum", "ICAP Aluminum (ppm Al)",
  "Iron", "ICAP Iron (ppm Fe)",
  "Sulfur", "ICAP sulfur (ppm S)", 
  "Zinc", "ICAP Zinc (ppm Zn)",
  "Manganese", "ICAP Manganese (ppm Mn)",
  "Copper", "ICAP Copper (ppm Cu)",
  "Magnesium", "ICAP Magnesium (ppm Mg)",
  "Sodium", "ICAP Sodium (ppm Na)",
  "MAC", "Microbially Active Carbon (%MAC)",
  "OrganicCN", "Organic C : Organic N",
  "OrganicNInorganicN", "Organic N : Inorganic N",
  "OrganicNRelease", "Organic Nitrogen Release (ppm N)",
  "OrganicPRelease", "Organic Phosphorus Release (ppm P)",
  "SoilHealthCalculation", "Soil Health Calculation",
  "AvailableN", "Available Nitrogen (lbs N/A)",
  "AvailableP", "Available Phosphorus (lbs P2O5/A)",
  "AvailableK", "Available Potassium (lbs K2O/A)")
```

# Z-transformed Nutrient Matrix
```{r}
# Prep dataframe
w.chem.ID=chem_wildfire%>%
  select(-OrganicNRelease, -OrganicPRelease, -SoilHealthCalculation, -OrganicNInorganicN, -WDRFBuffer, -OrganicNReserve, -OrganicPReserve, -SampleID, -Date, -TotalDNAID, -Timepoint, -Location, -Habitat, -Plot, -SubPlot, -Treatment, -ASV_ID, -DaysAfterFire)

# Remove variables with no variation, z-transform each variable, and format it as a matrix
# THIS INCLUDES THE CHEMICAL PROPERTIES FROM T1, SO A LOT ARE MISSING (because we did A&L for T1)
# I need to redo this by removing T1 as well
w.nut.mtx <- nutmtx(w.chem.ID)
w.chem.map <- chem_wildfire[, -c(10:45)]
w.chem.map = left_join(w.chem.map,w.nut.mtx,by="ViromeID")
w.nut.mtx <- w.nut.mtx[,-1]
w.nut.mtx <- as.matrix(w.nut.mtx)

saveRDS(w.nut.mtx, "C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/w.nut.mtx.RDS")
```

# Correlation b/t microbiome and chemical properties
```{r}
lnu.phylum.long <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/lnu_phylum_long.RDS")
lnu.phylum.long=lnu.phylum.long%>%
  select(-NewPhylum)
microbiome_data <- lnu.phylum.long %>%
  pivot_wider(names_from = Phylum, values_from = counts, values_fill = list(counts = 0))
microbiome_data <- as.data.frame(microbiome_data)
values_to_remove <- c("FIRE062", "FIRE063", "FIRE064", "FIRE065", "FIRE066", "FIRE067", "FIRE068", "FIRE069")
microbiome_data <- microbiome_data %>% filter(!ASV_ID %in% values_to_remove)

chemical_data=chem_wildfire%>%
  select(-OrganicNRelease, -OrganicPRelease, -SoilHealthCalculation, -OrganicNInorganicN, -WDRFBuffer, -OrganicNReserve, -OrganicPReserve, -SampleID, -Date, -TotalDNAID, -Timepoint, -Location, -Habitat, -Plot, -SubPlot, -Treatment, -ViromeID)

wildfire_asv_map <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/wildfire_asv_map.RDS")
wildfire_asv_map=wildfire_asv_map %>%
  select(-Moisture, -DNA)
wildfire_asv_map <- wildfire_asv_map[!(wildfire_asv_map$TimePoint=="T1"),]
chemical_data = left_join(wildfire_asv_map, chemical_data, by="ASV_ID")
chemical_data <- chemical_data[, -c(1:11)]

# Check that the dataframes have the same row names
identical(chemical_data$ASV_ID, microbiome_data$ASV_ID)

# Remove ID columns
microbiome_data <- microbiome_data %>% select(-ASV_ID)
chemical_data <- chemical_data %>% select(-ASV_ID)

# Compute the correlation matrix
cor_matrix <- rcorr(as.matrix(microbiome_data), as.matrix(chemical_data))
cor_values <- cor_matrix$r
cor_pvalues <- cor_matrix$P

microbiome_indices <- c(1:32)
chemical_indices <- c(33:61)
cor_values_subset <- cor_values[microbiome_indices, chemical_indices]
cor_pvalues_subset <- cor_pvalues[microbiome_indices, chemical_indices]
sig_matrix <- ifelse(cor_pvalues_subset < 0.05, "*", "")

# Create a combined data frame with correlations and p-values
cor_values[is.na(cor_values_subset)] <- 0  # Replace NA correlations with 0 for visualization

p <- pheatmap(cor_values_subset,
   clustering_distance_rows = "euclidean",
   clustering_distance_cols = "euclidean",
   clustering_method = "complete",
   main = "Correlation Heatmap of Microbiome and Chemical Properties",
   color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100),
  display_numbers = sig_matrix)

ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/HeatMap_Dendrogram/16S_correlation_heatmap.pdf", plot = p$gtable, width = 10, height = 8)
```

### THIS ISN'T WORKING
# I dont know how to deal with this...
# Correlation b/t host phylum prediction and chemical properties 
```{r}
otu.phylum.long <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/otu.phylum.long.RDS")
microbiome_data <- otu.phylum.long %>%
  pivot_wider(names_from = HostPhylum, values_from = RelAbd, values_fill = list(RelAbd = 0))
microbiome_data <- as.data.frame(microbiome_data)

  
chemical_data <- w.chem.ID
colnames(chemical_data)[colnames(chemical_data) == "SampleID"] <- "MapID"
chemical_data = left_join(w.chem.map, chemical_data, by="MapID")
chemical_data <- chemical_data[, -c(2:14)]

# Check that the dataframes have the same row names
identical(chemical_data$ID, microbiome_data$ID)

# Remove ID columns
microbiome_data <- microbiome_data %>% select(-ID)
chemical_data <- chemical_data %>% select(-ID)

# Compute the correlation matrix
cor_matrix <- rcorr(as.matrix(microbiome_data), as.matrix(chemical_data))
cor_values <- cor_matrix$r
cor_pvalues <- cor_matrix$P

microbiome_indices <- c(1:30)
chemical_indices <- c(31:59)
cor_values_subset <- cor_values[microbiome_indices, chemical_indices]
cor_pvalues_subset <- cor_pvalues[microbiome_indices, chemical_indices]
sig_matrix <- ifelse(cor_pvalues_subset < 0.05, "*", "")

# Create a combined data frame with correlations and p-values
cor_values[is.na(cor_values_subset)] <- 0  # Replace NA correlations with 0 for visualization

p <- pheatmap(cor_values_subset,
   clustering_distance_rows = "euclidean",
   clustering_distance_cols = "euclidean",
   clustering_method = "complete",
   main = "Correlation Heatmap of Microbiome and Chemical Properties",
   color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100),
  display_numbers = FALSE)

ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/HeatMap_Dendrogram/virome_correlation_heatmap.pdf",
       plot = p$gtable, width = 10, height = 8)
```

```{r}
#Calculate the environmental distance and filter redundant values
w.nut.dist <- as.matrix(dist(w.nut.mtx, method = "euclidean"))
w.nut.pca=cmdscale(w.nut.dist, eig = TRUE)
pcavariance(w.nut.pca, 1)
pcavariance(w.nut.pca, 2)
w.nut.pca$points
w.nut.pca.points=data.frame(w.nut.pca$points)
colnames(w.nut.pca.points)=c("pca1", "pca2")
wildfire_map_095 <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/input data/wildfire_map_095.RDS")
w.map.pca <- pca.map(w.nut.pca.points,wildfire_map_095)

# run PERMANOVAs
variables <- c("Habitat", "Treatment", "Location")
adonis.results <- run_adonis(variables, w.nut.dist, w.map.pca)
adonis.table <- do.call(rbind, adonis.results)

# PCA plot
w <- ggplot(w.map.pca, aes(x=pca1, y=pca2, color=Treatment, shape = Habitat, frame = TimePoint))+
  geom_point(size = 5)+
  xlab("PCA1, 39.07% Variance Explained")+
  ylab("PCA2, 15.11% Variance Explained")+
  ggtitle("PCA of Environmental Data - LNU Dataset") +
  scale_color_manual(values=pf_treatment_color, limits=pf_treatment_order) +
  theme_bw() +
  theme(axis.title = element_text(size = 18)) +
  theme(legend.text = element_text(size = 20)) +
  theme(legend.title = element_text(size = 20)) +
  theme(axis.text = element_text(size = 15))

### ADD LOADINGS

ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/PCA/LNU_PCA.pdf", width = 200, height = 125, units = "mm", dpi = 500)

w_habitat <- ggplot(w.map.pca, aes(x=pca1, y=pca2, color=Habitat, shape = Location, frame = TimePoint))+
  geom_point(size = 5)+
  xlab("PCA1, 39.07% Variance Explained")+
  ylab("PCA2, 15.11% Variance Explained")+
  ggtitle("PCA of Environmental Data - LNU Dataset") +
  scale_color_manual(values=Habitat_Color, limits=Habitat_Order) +
  theme_bw() +
  theme(axis.title = element_text(size = 18)) +
  theme(legend.text = element_text(size = 20)) +
  theme(legend.title = element_text(size = 20)) +
  theme(axis.text = element_text(size = 15))
```

#REDO PCA WITH PRINCOMP
```{r}
pca.w.nut.mtx <- as.data.frame(w.nut.mtx) %>%
  select(Moisture, SoilpH, OrganicMatter, AvailableP, Calcium, Magnesium, Potassium, Sodium)
pca_fit <- princomp(pca.w.nut.mtx, cor = TRUE)
scores <- as.data.frame(pca_fit$scores)
scores$Comp.1 <- -scores$Comp.1
pca_variance <- pca_fit$sdev^2 / sum(pca_fit$sdev^2)
w_pca_scores <- scores %>%
  select(Comp.1, Comp.2)
w_pca_scores <- rownames_to_column(w_pca_scores, var = "SampleID")
w_pca_map <- chem_wildfire %>%
  select(Location, Habitat, Treatment, Plot, SubPlot, Date, Timepoint, DaysAfterFire, ViromeID)
w_pca_map <- w_pca_map %>%
   rename(SampleID = ViromeID)
w_pca_map=left_join(w_pca_map,w_pca_scores,by="SampleID")
loadings <- as.data.frame(pca_fit$loadings[, 1:2])
loadings$Comp.1 <- -loadings$Comp.1
w_pca_map$Habitat <- as.factor(w_pca_map$Habitat)
print(names(w_pca_map))
print(names(loadings))
print(head(w_pca_map))
print(head(loadings))
library(ggnewscale)

pca_plot <- ggplot(w_pca_map, aes(x = Comp.1, y = Comp.2, color = Treatment)) +
  geom_point(size = 3) + # Plot individual samples
  scale_color_manual(values = pf_treatment_color, limits = pf_treatment_order) +
  geom_segment(data = loadings,
              aes(x = 0, y = 0, xend = Comp.1 * 6, yend = Comp.2 * 6),  # Scale the vectors for better visibility
              arrow = arrow(length = unit(0.2, "cm")),
              color = "black", linewidth = 0.5, alpha = 0.25) +
  geom_text(data = loadings, 
            aes(x = Comp.1 * 6, y = Comp.2 * 6, label = rownames(loadings)), 
            vjust = 1.5, color = "black") +
  labs(title = "PCA Plot with Variable Vectors",
       x = "PCA1, 34.14% Variance Explained",
       y = "PCA2, 18.83% Variance Explained") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18),
    axis.title.x = element_text(size = 18),
    axis.title.y = element_text(size = 18),
    axis.text.x = element_text(size = 18),
    axis.text.y = element_text(size = 18),
    legend.title = element_text(size = 18),
    legend.text = element_text(size = 18), 
    legend.position = "bottom"
  )


ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/PCA/LNU_PCA.pdf", width = 220, height = 150, units = "mm", dpi = 500)
```


# DISTANCE DATA
```{r}
wildfire_map_all <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/wildfire_map_all.RDS")

wildfire_gps <- wildfire_map_all %>%
  mutate(longitude = case_when(
    Plot == "MC1" ~ "-122.340161", 
    Plot == "MC2" ~ "-122.342634",
    Plot == "MC3" ~ "-122.443250", 
    Plot == "MC4" ~ "-122.4446",
    Plot == "MW1" ~ "-122.340566", 
    Plot == "MW2" ~ "-122.343707",
    Plot == "MW3" ~ "-122.4304", 
    Plot == "MW4" ~ "-122.4271",
    Plot == "QC1" ~ "-122.14871", 
    Plot == "QC2" ~ "-122.151743",
    Plot == "QW1" ~ "-122.149034", 
    Plot == "QW2" ~ "-122.151481", 
    SubPlot == "McL_1_1" ~ "-122.426317",
    SubPlot == "McL_1_2" ~ "-122.425650",
    SubPlot == "McL_6_1" ~ "-122.450933",
    SubPlot == "McL_6_2" ~ "-122.450933",
    SubPlot == "QR_1_1" ~ "-122.135167",
    SubPlot == "QR_1_2" ~ "-122.148317",
    SubPlot == "QR_2_2" ~ "-122.148700"))

wildfire_gps <- wildfire_gps %>%
  mutate(latitude = case_when(
    Plot == "MC1" ~ "38.838557", 
    Plot == "MC2" ~ "38.837889",
    Plot == "MC3" ~ "38.878067", 
    Plot == "MC4" ~ "38.8793",
    Plot == "MW1" ~ "38.837190", 
    Plot == "MW2" ~ "38.837483",
    Plot == "MW3" ~ "38.873683", 
    Plot == "MW4" ~ "38.874267",
    Plot == "QC1" ~ "38.482902", 
    Plot == "QC2" ~ "38.482457",
    Plot == "QW1" ~ "38.483063", 
    Plot == "QW2" ~ "38.48313", 
    SubPlot == "McL_1_1" ~ "38.874650",
    SubPlot == "McL_1_2" ~ "38.874550",
    SubPlot == "McL_6_1" ~ "38.882317",
    SubPlot == "McL_6_2" ~ "38.882233",
    SubPlot == "QR_1_1" ~ "38.482867",
    SubPlot == "QR_1_2" ~ "38.482817", 
    SubPlot == "QR_2_2" ~ "38.483150"))

quail_gps <- wildfire_gps[!(wildfire_gps$Location=="McLaughlin"),] 
quail_locations <- quail_gps %>%
  distinct(Plot, .keep_all = TRUE) %>%
  arrange(Plot)
quail_locations <- quail_locations %>%
  select(Plot, longitude, latitude)

mcl_gps <- wildfire_gps[!(wildfire_gps$Location=="Quail Ridge"),] 
mcl_locations <- mcl_gps %>%
  distinct(Plot, .keep_all = TRUE) %>%
  arrange(Plot)
mcl_locations <- mcl_locations %>%
  select(Plot, longitude, latitude)

wildfire_sample_locations <- wildfire_gps %>%
  distinct(Plot, .keep_all = TRUE) %>%
  arrange(Plot)
wildfire_sample_locations <- wildfire_sample_locations %>%
  select(Plot, longitude, latitude)

saveRDS(wildfire_sample_locations, "C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/input data/wildfire_gps_data.RDS")
write.csv(wildfire_sample_locations, "C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/sample.locations.csv")

wildfire_gps <- wildfire_gps[!(wildfire_gps$Virome=="no"),]

wildfire_gps <- wildfire_gps %>%
  select(ViromeID, longitude, latitude)

wildfire_gps <- column_to_rownames(wildfire_gps, var = "ViromeID")
wildfire_gps <- as.data.frame(wildfire_gps)
wildfire_gps$longitude <- as.numeric(wildfire_gps$longitude)
wildfire_gps$latitude <- as.numeric(wildfire_gps$latitude)
dist_matrix_vinellips <- distm(wildfire_gps, fun = distVincentyEllipsoid)
rownames(dist_matrix_vinellips) <- colnames(dist_matrix_vinellips) <- rownames(wildfire_gps)
```

# SAMPLE LOCATIONS
```{r}
library(ggplot2)
library(sf)
library(ggspatial)
library(rosm)
library(prettymapr)

sample_sf <- st_as_sf(wildfire_sample_locations, coords = c("longitude", "latitude"), crs = 4326)
ggplot() +
  annotation_map_tile(type = "osm", zoom = 13) +
  geom_sf(data = sample_sf, aes(geometry = geometry), color = "black", size = 1.25) +
  annotation_scale(location = "bl", width_hint = 0.5) +  # Adding a scale bar
  annotation_north_arrow(location = "tl", which_north = "true", 
                         pad_x = unit(1.7, "in"), pad_y = unit(0.05, "in"),
                         style = north_arrow_fancy_orienteering) +  # Adding a north arrow
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  labs(title = "Sample Locations",
       subtitle = "Study area with sample points")

ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/Maps/full_map.pdf", width = 200, height = 125, units = "mm", dpi = 500)

# Quail Ridge Subset
add_rows <- data.frame(Plot = c("x", "y"), longitude = c(-122.1486449, -122.148692), latitude = c(38.48450498,38.480886))
quail_locations <- rbind(quail_locations, add_rows)

quail_sf <- st_as_sf(quail_locations, coords = c("longitude", "latitude"), crs = 4326)


ggplot() +
  annotation_map_tile(type = "osm", zoom = 50) +
  geom_sf(data = quail_sf, aes(geometry = geometry), color = "white", size = 3) +
  annotation_scale(location = "br", width_hint = 0.5) +  # Adding a scale bar
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank()
  )

ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/Maps/quail_map.pdf", width = 200, height = 125, units = "mm", dpi = 500)

# McLaughlin Subset
mcl_sf <- st_as_sf(mcl_locations, coords = c("longitude", "latitude"), crs = 4326)
ggplot() +
  annotation_map_tile(type = "osm", zoom = 15) +
  geom_sf(data = mcl_sf, aes(geometry = geometry), color = "white", size = 3) +
  annotation_scale(location = "bl", width_hint = 0.5) +  # Adding a scale bar
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank()
  )


ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/Maps/mclaughlin_map.pdf", width = 200, height = 125, units = "mm", dpi = 500)
```


# DISTANCE DECAY (VIROMES)
```{r}
pf.otu.dist <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/pf.otu.dist.RDS")
bray_dist_matrix <- as.matrix(pf.otu.dist)
physical_dist_matrix <- dist_matrix_vinellips

bray_dist_vector <- as.vector(as.dist(pf.otu.dist))
physical_dist_vector <- as.vector(as.dist(dist_matrix_vinellips))
bray_sim_vector <- 1 - bray_dist_vector

cor_test_result <- cor.test(physical_dist_vector, bray_sim_vector)
model <- lm(bray_sim_vector ~ physical_dist_vector)
model_summary <- summary(model)

slope <- model_summary$coefficients[2,1]
p_value <- coef(summary(model))[2,4]
correlation_coefficient <- cor_test_result$estimate

plot_data <- data.frame(PhysicalDistance = physical_dist_vector, BrayCurtisSimilarity = bray_sim_vector)

ggplot(plot_data, aes(x = physical_dist_vector, y = bray_sim_vector)) +
  geom_point()+
  geom_smooth(method = "lm", col = "black") +
  labs(
    title = "Distance Decay of Bray-Curtis Similarity",
    x = "Physical Distance (meters)",
    y = "Bray-Curtis Similarity",
  ) +
  theme_bw() +
  annotate("text", x = Inf, y = Inf, label = paste0("p-value = ", format(p_value, scientific = TRUE)), hjust = 2, vjust = 2.5, size = 5) + 
  annotate("text", x = Inf, y = Inf, label = sprintf("slope = %.3e", round(slope, 3)), hjust = 2.4, vjust = 3.7, size = 5) + 
  annotate("text", x = Inf, y = Inf, label = paste0("r = ", round(correlation_coefficient, 3)), hjust = 4.2, vjust = 4.9, size = 5)

ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/ScatterPlot/distance_decay_virome.pdf", width = 200, height = 125, units = "mm", dpi = 500)
```

