---
title: "Ch3Wildfire_16S"
output: html_document
date: "2024-06-27"
---
```{r}
# LOAD PACKAGES
library(tidyverse)
library(vegan)
library(dplyr)
library(ggplot2)
library(factoextra)
library(gridExtra)
library(cowplot)
library(ComplexUpset)

# Load RDS files
lnu.asv <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/lnu.asv.RDS")
tax_filtered <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/tax_filtered.RDS")
wildfire_asv_map <- readRDS("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/wildfire_asv_map.RDS")
```

# PCoA: ALL DATA ... do this before taxonomy 
```{r}
# create rarefaction curve to determine rarefaction threshold for abundance table
# don't need to run the below code every time, only the first time to figure out what to rarefy to
#asv.rarecurve <- rarecurve(t(lnu.asv), step = 100) 
#x <- map_dfr(asv.rarecurve, bind_rows) %>% bind_cols(colnames(lnu.asv),.)
#x <- as.data.frame(x)
#row.names(x) <- x[, 1]

#based on x dataframe, choose sample size to rarefy to
set.seed(24)
asv.rare <- t(rrarefy(t(lnu.asv), sample = 17700))

# remove singletons --> 4,933 contigs
asv.rare <- data.frame(asv.rare) %>%
  rmv_sngl()

#bray-curtis dissimilarity distance matrix 
asv.dist=vegdist(t(asv.rare), method = "bray")
asv.pcoa <- pcoa(asv.dist)
asv.pcoa.points <- pcoa.points(asv.pcoa)
asv.map <- pcoa.map.asv(asv.pcoa.points, wildfire_asv_map)
variance(asv.pcoa, 1)
variance(asv.pcoa, 2)

pcoa.treatment.habitat(asv.map, x_col = pcoa1, y_col = pcoa2, color_col= Treatment, shape_col = Habitat, x_label = "20.89% Variance Explained", y_label = "11.47% Variance Explained", title = "All LNU 16S rRNA ASV Profile", filename = "C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/PCoA/prokaryotes/all_LNU_ASV_pcoa_treatment_habitat.pdf")

pcoa.treatment.time(asv.map, x_col = pcoa1, y_col = pcoa2, color_col= Treatment, shape_col = TimePoint, x_label = "20.89% Variance Explained", y_label = "11.47% Variance Explained", title = "All LNU 16S rRNA ASV Profile", filename = "C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/PCoA/prokaryotes/all_LNU_ASV_pcoa_treatment_time.pdf")

pcoa.habitat.location(asv.map, x_col = pcoa1, y_col = pcoa2, color_col= Habitat, shape_col = Location, x_label = "20.89% Variance Explained", y_label = "11.47% Variance Explained", title = "All LNU 16S rRNA ASV Profile", filename = "C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/PCoA/prokaryotes/all_LNU_ASV_pcoa_habitat_location.pdf")

# run PERMANOVAs
variables <- c("Habitat", "Treatment", "Location")
adonis.results <- run_adonis(variables, asv.dist, asv.map)
adonis.table <- do.call(rbind, adonis.results)

```

# Taxonomy Stacked Bar Plot: ALL DATA (2021 + 2022)
```{r}
# add OTU_ID back onto asv.rare
asv.rare$OTU_ID <- rownames(asv.rare)

# Join taxonomy and abundance data together
tax_lnu <- left_join(asv.rare, tax_filtered, by = "OTU_ID")
# make sure asv.rare is in the same order as tax_lnu (return = TRUE)
check_column <- "OTU_ID"
all(asv.rare[[check_column]] == tax_lnu[[check_column]])
unique(tax_lnu$Phylum)

# pivot table and group by Phylum
tax_lnu.long <- pivot_longer(tax_lnu, cols=1:87, names_to = "ASV_ID", values_to = "counts")
lnu.phylum.long <- group_by(tax_lnu.long, Phylum, ASV_ID) %>%
  summarize(counts=sum(counts))

# collapse phyla into "other" category if represents less than 2%, which is 354 (rarefied to 17,700)
lnu.phylum.long$Phylum <- as.character(lnu.phylum.long$Phylum)
lnu.phylum.long <- lnu.phylum.long %>%
  group_by(Phylum) %>%
  mutate(NewPhylum = ifelse(all(counts < 354), 'Other', Phylum)) %>%
  ungroup()
# find out which phyla are represented (used for making legend)
unique(lnu.phylum.long$NewPhylum)

saveRDS(lnu.phylum.long, "C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/rds/lnu_phylum_long.RDS")

# Prep data frame for plotting
lnu.phylum.map <- merge(lnu.phylum.long, wildfire_asv_map, by="ASV_ID")

# Plot
lnu_phylum <- ggplot(lnu.phylum.map, aes(x=Treatment, y=counts, fill=NewPhylum))+
    labs(x="Treatment", 
       y ="Counts",
       title = "LNU 16S rRNA ASV Profile")+
  geom_bar(stat="identity", position = "fill")+
  scale_fill_manual(values=collapsed_phylum_colors) +
  theme_bw() +
  #theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~ Habitat)

lnu_phylum

lnu_phylum <- ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/StackedBar/lnu_phylum.pdf", width = 200, height = 150, units = "mm", dpi = 500)

ggplot(lnu.phylum.map, aes(x=TimePoint, y=counts, fill=NewPhylum))+
    labs(x="TimePoint", 
       y ="Counts",
       title = "LNU 16S rRNA ASV Profile")+
  geom_bar(stat="identity", position = "fill")+
  scale_fill_manual(values=collapsed_phylum_colors) +
  theme_bw() +
  #theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(Habitat ~ Treatment)

ggsave("C:/Users/segeo/Box Sync/EmersonLab/Research/Ch3Wildfire/R_Figures/pdf/StackedBar/lnu_phylum_timepoint.pdf", width = 200, height = 150, units = "mm", dpi = 500)
```
# Phylum-level stats - Chaparral - Treatment
```{r}
phylum.asv.stats <- lnu.phylum.map

ch.acido_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Acidobacteriota" & Habitat == "Chaparral")
ch.actino_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Actinobacteriota" & Habitat == "Chaparral")
ch.bact_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Bacteroidota" & Habitat == "Chaparral")
ch.chloro_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Chloroflexota" & Habitat == "Chaparral")
ch.crena_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Crenarchaeota" & Habitat == "Chaparral")
ch.firm_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Firmicutes" & Habitat == "Chaparral")
ch.gemma_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Gemmatimonadota" & Habitat == "Chaparral")
ch.myxo_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Myxococcota" & Habitat == "Chaparral")
ch.planc_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Planctomycetota" & Habitat == "Chaparral")
ch.proteo_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Proteobacteria" & Habitat == "Chaparral")
ch.verru_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Verrucomicrobiota" & Habitat == "Chaparral")

kruskal.test(counts ~ Treatment, ch.acido_phylum.asv)
kruskal.test(counts ~ Treatment, ch.actino_phylum.asv)
kruskal.test(counts ~ Treatment, ch.bact_phylum.asv)
kruskal.test(counts ~ Treatment, ch.chloro_phylum.asv)
kruskal.test(counts ~ Treatment, ch.crena_phylum.asv)
kruskal.test(counts ~ Treatment, ch.firm_phylum.asv)
kruskal.test(counts ~ Treatment, ch.gemma_phylum.asv)
kruskal.test(counts ~ Treatment, ch.myxo_phylum.asv)
kruskal.test(counts ~ Treatment, ch.planc_phylum.asv)
kruskal.test(counts ~ Treatment, ch.proteo_phylum.asv)
kruskal.test(counts ~ Treatment, ch.verru_phylum.asv)
```

# Phylum-level stats - Chaparral - Time Series
```{r}
b.ch.acido_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Acidobacteriota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.actino_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Actinobacteriota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.bact_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Bacteroidota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.chloro_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Chloroflexota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.crena_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Crenarchaeota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.firm_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Firmicutes" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.gemma_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Gemmatimonadota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.myxo_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Myxococcota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.planc_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Planctomycetota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.proteo_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Proteobacteria" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")
b.ch.verru_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Verrucomicrobiota" & Habitat == "Chaparral" & Treatment == "AfterBurn_Wildfire")

kruskal.test(counts ~ TimePoint, b.ch.acido_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.actino_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.bact_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.chloro_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.crena_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.firm_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.gemma_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.myxo_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.planc_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.proteo_phylum.asv)
kruskal.test(counts ~ TimePoint, b.ch.verru_phylum.asv)
```

# Phylum-level stats - Woodland - Treatment
```{r}
wo.acido_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Acidobacteriota" & Habitat == "Woodland")
wo.actino_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Actinobacteriota" & Habitat == "Woodland")
wo.bact_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Bacteroidota" & Habitat == "Woodland")
wo.chloro_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Chloroflexota" & Habitat == "Woodland")
wo.crena_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Crenarchaeota" & Habitat == "Woodland")
wo.firm_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Firmicutes" & Habitat == "Woodland")
wo.gemma_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Gemmatimonadota" & Habitat == "Woodland")
wo.myxo_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Myxococcota" & Habitat == "Woodland")
wo.planc_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Planctomycetota" & Habitat == "Woodland")
wo.proteo_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Proteobacteria" & Habitat == "Woodland")
wo.verru_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Verrucomicrobiota" & Habitat == "Woodland")

kruskal.test(counts ~ Treatment, wo.acido_phylum.asv)
kruskal.test(counts ~ Treatment, wo.actino_phylum.asv)
kruskal.test(counts ~ Treatment, wo.bact_phylum.asv)
kruskal.test(counts ~ Treatment, wo.chloro_phylum.asv)
kruskal.test(counts ~ Treatment, wo.crena_phylum.asv)
kruskal.test(counts ~ Treatment, wo.firm_phylum.asv)
kruskal.test(counts ~ Treatment, wo.gemma_phylum.asv)
kruskal.test(counts ~ Treatment, wo.myxo_phylum.asv)
kruskal.test(counts ~ Treatment, wo.planc_phylum.asv)
kruskal.test(counts ~ Treatment, wo.proteo_phylum.asv)
kruskal.test(counts ~ Treatment, wo.verru_phylum.asv)
```

# Phylum-level stats - Woodland - Time Series
```{r}
b.wo.acido_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Acidobacteriota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.actino_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Actinobacteriota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.bact_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Bacteroidota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.chloro_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Chloroflexota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.crena_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Crenarchaeota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.firm_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Firmicutes" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.gemma_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Gemmatimonadota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.myxo_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Myxococcota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.planc_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Planctomycetota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.proteo_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Proteobacteria" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")
b.wo.verru_phylum.asv <- phylum.asv.stats %>%
  filter(Phylum == "Verrucomicrobiota" & Habitat == "Woodland" & Treatment == "AfterBurn_Wildfire")

kruskal.test(counts ~ TimePoint, b.wo.acido_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.actino_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.bact_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.chloro_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.crena_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.firm_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.gemma_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.myxo_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.planc_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.proteo_phylum.asv)
kruskal.test(counts ~ TimePoint, b.wo.verru_phylum.asv)
```